# Generated by Django 5.0.1 on 2024-06-08 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0001_initial'),
        ('turma', '0002_turma_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='turma',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='turma.turma'),
        ),
    ]
