# Generated by Django 5.0.1 on 2024-06-08 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0002_alter_disciplina_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='turma',
        ),
    ]
