# Generated by Django 5.0.1 on 2024-06-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direcao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direcao',
            options={'verbose_name': 'Diretor(a)'},
        ),
    ]
