# Generated by Django 5.0.1 on 2024-07-14 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0003_remove_disciplina_turma'),
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disciplina.disciplina'),
        ),
    ]
